### ISSUE TITLE
Text enlargement + Draw Icons cant be disabled.

### ISSUE THREAD

**Issue by TheRealZeagan** [IlliumIv/HeistIcons#3]
Hello

The function "Draw icon to world" cant be disabled even if its unchecked. 

And the Text cant be increased only the background "The white background" Could you make it so the text itself can be larger too?
Like "Essences" and "Currency" etc.

**Comment by IlliumIv** [comment]
Hi.

> The function "Draw icon to world" cant be disabled even if its unchecked.

It work correctly. Probably you use Queuete fork. If it true, try to report here: https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/922954-exileapi-3-12-release-12.html

> Could you make it so the text itself can be larger too?

No, ExileApi not allowed it. You can change font in Core settings page, it's all.
